### ISSUE TITLE
Plugin openshift does not work with Che 5.0.0

### ISSUE THREAD

**Issue by ghost** [codenvy/plugin-openshift#36]
The majority of functions are grayed out. Multiple issues include no mixin when converting a project to openshift, no connection of workspace projects with openshift projects.

**Comment by bmicklea** [comment]
Thanks @eivantsov for testing this - who's team would deal with this?

**Comment by rajasekaran07** [comment]
@eivantsov 

Kindly let me know if you have ETA for this issue...

**Comment by bmicklea** [comment]
@rajasekaran07 a team has taken this in their next sprint which begins on Thursday and runs for two weeks. There are a number of issues here so it's too early to say when all will be completed but we will keep the issues updated as progress is made.

**Comment by rajasekaran07** [comment]
@Brad,
Thanks for your update. Please keep update on this thread. I am eagerly
waiting for this.

Regards,
Raja

**Comment by bmicklea** [comment]
Will do @rajasekaran07 - just out of curiosity are you using OpenShift in your organization?

**Comment by rajasekaran07** [comment]
Yes we are using openshift 3.0

**Comment by bmicklea** [comment]
Can you tell me which organization are you with?

**Comment by rajasekaran07** [comment]
I am from Bcause Enterprise Pvt.Ltd NewDelhi, India

**Comment by rajasekaran07** [comment]
@bmicklea I am curious to know if you have any update on this issue...

**Comment by rajasekaran07** [comment]
@bmicklea @evidolob any update on this issue.. I am waiting for your response.

**Comment by TylerJewell** [comment]
It is in the current sprint. The current plugin compiles and generates an assembly.  Instructions on how to package it for Codenvy are coming.

**Comment by rajasekaran07** [comment]
Is openshift plugin issue is resolved?? Please let me know the correct Che
version to use.

Regards,
Raja
9540364913

On 18-Oct-2016 8:05 pm, "James Drummond" notifications@github.com wrote:

Closed #36 https://github.com/codenvy/plugin-openshift/issues/36.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/codenvy/plugin-openshift/issues/36#event-827585338,
or mute
the thread

**Comment by TylerJewell** [comment]
Yes, the plugin openshift has been tested and certified to work with che 5.0.0 and the latest version of openshift.   @JamesDrummond @eivantsov and the team that did the testing will be posting instructions on how to get the latest binary (or build it yourself) and integrate it into the latest version of Che.   We are targeting this to be completed for docs by the completion of M6, which are hoping is this week.

@JamesDrummond - do you have the tracking issue for docs & ensuring that the install package is linked to the right place to get the 5.0 version, along with docs updates on how to build the plugin directly.

**Comment by rajasekaran07** [comment]
@TylerJewell  & Team,

Congrats for the greatest achievement. Kindly share the complete document URL once it is available. 
We are using Openshift 3.1.1. in my organisation. 

Regards,
Raja

**Comment by TylerJewell** [comment]
James is going to open up an epic that tracks all of the remaining docs and pm tasks needed to make this a quality shippable release.

**Comment by rajasekaran07** [comment]
@JamesDrummond can you please provide the document URL to implement openshift plugin in che.
I already tried with https://eclipse-che.readme.io/v5.0/docs/openshift-config but it is not working.
Regards,
Raja

**Comment by JamesDrummond** [comment]
@rajasekaran07 We are currently working on bugs. The openshift plugin is not currently working. You can track issue at https://github.com/eclipse/che/issues/2834 . Once the bugs are resolved I will test and update the documentation if needed.
