### ISSUE TITLE
boss-eap64-openshift:1.4 image not found

### ISSUE THREAD

**Issue by ashumilova** [codenvy/plugin-openshift#43]
![image](https://cloud.githubusercontent.com/assets/1611939/19931541/8857956e-a115-11e6-9a69-9262332cdf3d.png)

Thus, Openshift templates, which use image boss-eap64-openshift:1.4 doesn't work.

**Comment by l0rd** [comment]
@ashumilova can you guide me through the steps to reproduce that error? 

I've just tried to install a sample application that uses `jboss-eap64-openshift:1.4` template on [ADB with OpenShift](https://github.com/projectatomic/adb-atomic-developer-bundle#how-do-i-install-and-run-adb) and it worked.

**Comment by ashumilova** [comment]
@l0rd tested those templates just now - and it works fine too. Maybe smth was fixed. Thank you, closing issue.
